version: '3.8'

services:
  app:
    image: phoenix:latest
    build: .
    command: >
      /bin/sh -c "iex -S mix phx.server"
    volumes:
      - .:/app
    ports:
      - "4001:4001"
    depends_on:
      - postgres_notifications
    networks:
      - shared_net

  postgres_notifications:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata_notifications:/var/lib/postgresql/data
    networks:
      - shared_net

volumes:
  pgdata_notifications:
  pgdata:       
  shared_storage:       

networks:
  shared_net:
    external: true
